### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by eeveefox** [haipit/haipit.news#1]
Более удобная навигация по страницам, сортировка по источникам

**Comment by EvilFreelancer** [comment]
Добрался я до Хайпита ;) есть предложения что имеешь ввиду? Согласен что надо поправил пагинацию и много чего ещё.

**Comment by EvilFreelancer** [comment]
Немного обновил интерфейс, починил наконец-таки пагинацию, плюс немного косметических штучек добавлено.
